### ISSUE TITLE
Cache expiration details 

### ISSUE THREAD

**Issue by feinstein** [Baseflow/flutter_cache_manager#139]
The Readme isn't clear on the behavior of expired cache items. When a file expire, does the library retry its download and what happens when it fails? Will show the cached image or will it delete the cached image and show an error?

What about the retries? Will it retry immediately or wait? Does it have exponential back off? Does it retry forever?

**Comment by renefloor** [comment]
@feinstein there is currently very little retry logic.
If you use getFile() it always returns the cached file. If that is outdated it tries to update the file. When it is successful it will also return that file (therefore it is a stream), otherwise it will try again the next time you will need that file. 

Cached files are only deleted when they aren't used for some time (the maxAgeCacheObject) or when there are too many files in the cache (sorted on oldest by touched).
Hope this is clear for you

**Comment by feinstein** [comment]
It does, but it would be nice to see this info on the Readme.

**Comment by pm-chqbook** [comment]
How to set expiry in CachednetworkImage
