### ISSUE TITLE
i can't install, "version solving failed"

### ISSUE THREAD

**Issue by incafox** [Baseflow/flutter_cache_manager#171]
## 🐛 Bug Report

hi, I can't install flutter_cache_manager, aparently there exist some kind of conflict with "flutter_plugin_pdf_viewer ^1.0.7".

After run flutter pub get im getting this error:

"So, because flutter_final_sri depends on both flutter_plugin_pdf_viewer ^1.0.7 and flutter_cache_manager ^1.2.2, version solving failed.
pub get failed (1; So, because flutter_final_sri depends on both flutter_plugin_pdf_viewer ^1.0.7 and flutter_cache_manager ^1.2.2, version solving failed.)
exit code 1"

Plugins that im using:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  pdf: ^1.4.1
  pdf_viewer_plugin: ^1.0.0+2
  path_provider: ^1.6.7
  http: ^0.12.1
  file_picker: ^1.4.3+2
  pull_to_refresh: ^1.5.8
  flutter_collapse: ^0.1.1
  card_settings: ^1.5.5
  shared_preferences: ^0.5.6+1
  flutter_form_builder: ^3.7.3
  flutter_plugin_pdf_viewer: ^1.0.7
  expandable: ^4.1.2
  flutter_pdfview: ^1.0.0+10
  email_validator: ^1.0.4
  flutter_email_sender: ^2.2.2
  provider: ^4.0.2
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.1+1
  flutter_launcher_icons: ^0.7.4
  flappy_search_bar: ^1.7.2
  flutter_downloader: ^1.4.4
  dio: ^3.0.9
  open_file: ^3.0.1
  flutter_cache_manager: ^1.2.2

What can i do? help pls

**Comment by renefloor** [comment]
It's because the pdf plugin doesn't support newer versions of rxDart it doesn't support the latest version of the cache manager.
![Screenshot_20200503-160724_Chrome~2](https://user-images.githubusercontent.com/15101411/80916361-75ba3f00-8d58-11ea-9819-8d5cf1e38084.png)

You could ask them to support rxDart up to 0.24, or downgrade your dependency of the cache manager to 1.1.3.
