### ISSUE TITLE
Why new versions have dependency on rxdart

### ISSUE THREAD

**Issue by singun-lxd** [Baseflow/flutter_cache_manager#176]
I don't think it's good for apps not using rxdart, it will increase app's size without any benefits

**Comment by renefloor** [comment]
The webhelper uses behaviorsubject to directly return the last known result when a new subscriber listens to the same url. Flutter does a pretty good job with tree shaking when building a release. I didn't test it, but if you can show me that a released app significantly grows in size because of this I'll consider removing the use of BehaviorSubject.
