### ISSUE TITLE
Windows and other desktop platform Support 

### ISSUE THREAD

**Issue by alionour** [Baseflow/flutter_cache_manager#272]
Feature Requests
Caching is required for desktop platforms 
add implementations for adding caching in windows linux macOS
Platforms: Windows , Linux , MacOS

**Comment by renefloor** [comment]
If you have any problems with desktop support please file a specific issue.

**Comment by tomekit** [comment]
I don't have enough details to file the specific issue, but in context of image caching I find: `JsonCacheInfoRepository` quite unusable.

I think it would be great to use the `CacheObjectProvider` caching instead of: `JsonCacheInfoRepository` on Windows and Linux.
This would require using the FFI for Sqflite: https://pub.dev/packages/sqflite_common_ffi though.

I was wondering if anyone started work already on incorporating SQLite FFI or perhaps there are any other approaches that could be used?
I've seen some work that: `sqflite` maintainer started, but it's pretty old:
https://github.com/Baseflow/flutter_cache_manager/compare/master...alextekartik:flutter_cache_manager:master
https://github.com/Baseflow/flutter_cached_network_image/compare/master...alextekartik:flutter_cached_network_image:master

Issues that I am finding on Linux.
-  The `~/local/share/com.package.id/libCachedImageData.json` file gets often corrupted, causing: `_readFile` to fail whilst parsing the JSON,
- There is some issue where not all cache object data lands in: `~/local/share/com.package.id/libCachedImageData.json`. In my case everytime I load multiple thumbnails of ~3-4MB size, cache entries get created in: `/tmp/libCachedImageData`, but: `libCachedImageData.json` doesn't contain references to them. There is probably some write concurrency issue which I didn't manage to find out.
This also makes my `/tmp` grow almost infinitely with new cache files being added and not properly referenced in: `libCachedImageData`.
- Cache path inconsistency, DB is being stored in: `~/local/share/com.package.id/libCachedImageData.json` where as the images are stored in e.g.: `/tmp/libCachedImageData/e26f86b1-9f60-11ed-ad54-9db9fd933c72.json`.
This is because the:  `getApplicationSupportDirectory` and  `getTemporaryDirectory` functions are used respectively to get the cache locations. 

I am writing that down not to complain, but more like a notes in case someone deals with similar issue or if I start work on integrating FFI myself.

**Comment by khomin** [comment]
<img width="489" alt="image" src="https://github.com/Baseflow/flutter_cache_manager/assets/7860640/b6f47f20-69f2-454d-a874-925f90b563a0">

I don't see windows support
Will it work for windows or it is ios only?
