### ISSUE TITLE
Questions about File Extension

### ISSUE THREAD

**Issue by shingohu** [Baseflow/flutter_cache_manager#74]
```
var fileExtension = "";
    if (response.hasHeader("content-type")) {
      var type = response.header("content-type").split("/");
      if (type.length == 2) {
        fileExtension = ".${type[1]}";
      }
    }
```
You get file extensions by content-type,for example. Doc's content-type is application/msword，so the stored file name is uuid.msword,I want the filename is uuid.doc,So I can't open it in my app.
Why do not use content-disposition to get filenames for locally stored filenames,or we can specify the file name of the local store?

```
 var fileExtension = "";
    if (response.hasHeader("content-disposition")) {
      var fileName = response
          .header("content-disposition")
          .split(";")[1]
          .split("=")[1]
          .replaceAll("\"", "");
      fileExtension = fileName.substring(fileName.lastIndexOf("."));
    } else if (response.hasHeader("content-type")) {
      var type = response.header("content-type").split("/");
      if (type.length == 2) {
        fileExtension = ".${type[1]}";
      }
    }
```

**Comment by badboy-tian** [comment]
+1

**Comment by badboy-tian** [comment]
I wang to get the fileExtension by url. for examle:  http://xxxx.com/xxx.mp3 ,  and the fileExtension should be mp3. any way to make this ?

**Comment by renefloor** [comment]
Will look into it

**Comment by LachlanGrant** [comment]
@renefloor is it possible we can manually override the file extension? I'm not too sure how the code above uses the fileExtensionVariable

**Comment by jimgreer** [comment]
I have the same issue. @renefloor you closed it but I'm still having the problem. Are you closing it as Will Not Fix?

**Comment by jimgreer** [comment]
+1

**Comment by nagoya0** [comment]
+1
content-type sometime contains not only MIME-type but also charset name or boundary string.
For example, stored file name have the potential to become "example.html; charset=utf-8".

**Comment by xilibro** [comment]
I have the same need。

**Comment by renefloor** [comment]
For most common mime-types this is fixed in version 1.2.1. You can see the content-types that are supported here: https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/web/mime_converter.dart

If one is missing you can create a pull request for that.

@LachlanGrant You can create your own FileService with a fixed fileExtension: https://github.com/Baseflow/flutter_cache_manager/blob/develop/lib/src/web/file_service.dart

@badboy-tian I have been thinking about getting the file extensions from other sources than content-type, for example the url, but decided that for now I won't do that. It is to tricky to cover all the cases, that would be a project on its own. You can do that yourself by creating a custom FileService and get the extension from the url.

**Comment by josejeria** [comment]
Can you please also add 'audio/x-aac' as 'aac' file extension ?
Thanks

**Comment by LachlanGrant** [comment]
@renefloor Perfect, thank you! a custom file service was what I was looking for :)

**Comment by renefloor** [comment]
@josejeria what should be the difference with audio/aac ?

**Comment by josejeria** [comment]
@renefloor it's related to coding. But both audio/aac and audio/x-aac have the same extension, 'aac'. Currently cache manager downloads and stores it as a ".x-aac" extension, and this does not exist.

**Comment by renefloor** [comment]
@josejeria Thanks. Next time you can also make a PR like #169 or #172 .

**Comment by jaweii** [comment]
Why don't just add a support like this:
CacheManager.download(url, extension: 'mp4');
